#+TITLE: LdBeth's Spacemacs Private Directory
#+STARTUP: SHOWALL
#+TAGS: News(n) View(v) Push(p) Pics(p) Emacs(e) ACG(a)

[[http://spacemacs.org][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]

[[file:evil.xpm]]


* Introduction
  This is the Spacemacs private directory of LdBeth, to use it, clone it
  to =~/.spacemacs.d/= or symbol link it to =~/.emacs.d/private/=.
  (It is recommended to use =dotspacemacs-directory=, for the sake 
  of a easier way to manage your personal files.)
  Or you can just get a copy and hack on this.

* Deprave Layer
  The Improved Spacemacs Layer.
  Here is some improvement of the existed problems of Spacemacs.

** multi-keys
   A key chord imput method.

** Gnus
   Added shadowed bindings to major mode prefix.

** Elfeed
   Bind =elfeed/split-show-next= and =elfeed/split-show-prev= to
   ~J~ and ~k~.

** Erc
   A little changes on timestamp.

** Chinese-pyim
   Automatic enable Chinese pyim input method.

** Company-ispell
   Guess words by using ispell/aspell.

** SLIME
   Use my preferred Clisp program.

** Eshell
   Added =pcomlete-extension= and =pcml-homebrew=.

** header2
   Auto make header.

* EMMS Layer
  The Emacs Media Manger Layer. It is pending and will be included
  in Spacemacs in the future. (Well, not yet.)

* Maxima Layer
  The Lisp Computer Algebra System. Not completed yet.

* Social Layer
  Configuration for Blog and Gitter, may add more packages soon.

** hexo.el
   Writing blogs using hexo as backend.
   ~SPC a b~ to start.

** Notmuch
   Maybe the best Mail index builder.

** WandeLust
   Yet another Emacs mail client.

* Utility Layer
  Network utility, including aira2 and eww. There are some problems
  on aria2.el.

** aria2.el
   A frontend to aria2. Currently there are some problems when
   working on macOS.

** eww
   Using Emacs to browse web.

** w3m
   An Emacs pager interface to w3m.

** Shimbun
   Japanese style news reader.

** namazu
   A text search engine.

** wc-mode
   Count words and set goals.

** Ledger
   Extra utility by =dklrt=.

** EVALATOR
   Modern REPL.

* Game Machine Layer
  Provide some games.

* all-the-icons Layer
  Provide fancy icons.

* RSS Feeds                                                          :elfeed:
  +I use elfeed-org to manage my RSS Feeds.+

  Now I use w3m Shimbun modulus to read RSS and Atom Feeds.

** News                                                               :News:
*** [[http://www.solidot.org/index.rss][Solidot]]
*** [[http://www.acgpiping.net/feed/][ACG 批评]]                                                            :ACG:

** Blogs
*** [[http://feed.williamlong.info/][月光博客]]
    感觉倒像是新闻站。

** Recommendations                                                    :Push:
*** [[http://animetaste.net/feed][Anime Taste]]                                                         :ACG:
   
** Music                                                               :ACG:
*** [[http://koe.anime-sharing.com/feed/][Anime Sharing]]

** Comics                                                             :Pics:
*** [[https://xkcd.com/rss.xml][xkcd]]
    Something Interesting.

** Emacs                                                             :Emacs:
*** [[http://www.emacsist.com/rss][Emacsist]]
*** [[http://planet.emacsen.org/atom.xml][Planet Emacsen]]
